version: '3.4'

services:
  db:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_DATABASE: "IVP"
      - MYSQL_USER: "IVP"
      - MYSQL_PASSWORD: "ivp"
      - MYSQL_ROOT_PASSWORD: "ivp"
    network_mode: host
    volumes:
      - ./mysql/localhost.sql:/docker-entrypoint-initdb.d/localhost.sql
  apache-php:
    image: php:7.2.2-apache
    container_name: apache_php
    depends_on:
      - db
    volumes:
      - ./php/:/var/www/html/
    network_mode: host
    stdin_open: true
    tty: true
  v2x-hub:
    image: animeshb27/v2x-hub:v2x-hub-v3.2
    container_name: v2x-hub
    depends_on:
      - apache-php
    network_mode: host
